### ISSUE TITLE
Is there any further documentation that doesn't use TS but plain and simple JS?

### ISSUE THREAD

**Issue by thepra** [antonmedv/codejar#10]
I would like to add line numbers but those instructions are all about TS and can't quite get how to do that in JS. It would be nice TS-less examples.

**Comment by antonmedv** [comment]
There is not so much doc for linenumbers. Only example. Maybe if you can understand it you can write docs? 


This is actually JavaScript (not TypeScript):
```js
import {CodeJar} from '@medv/codejar';
import Prism from 'prismjs';

// Import line numbers helper.
import {withLineNumbers} from '@medv/codejar/linenumbers';

const node = document.querySelector('.editor');

// Wrap highlighting function to show line numbers.
const jar = new CodeJar(
  node,
  withLineNumbers(Prism.highlightElement)
);
```
