### ISSUE TITLE
missing line numbers

### ISSUE THREAD

**Issue by julianpoemp** [antonmedv/codejar#102]
as far as I can see `linenumbers.js` was deleted in a previous commit. Was this intended? Is there any plan to add support for line numbers again?

**Comment by antonmedv** [comment]
Nope. I kinda disliked this line-numbers implementation. I think line numbers can be easily added by third-party packages like `codejar-linenumbers`.

**Comment by julianpoemp** [comment]
@antonmedv I was just wondering because I couldn't find any information or braking change about linenumbers.

Where can I find the `codejar-linenumbers` package? On npm I found [nothing](https://www.npmjs.com/search?q=codejar-linenumbers).

**Comment by antonmedv** [comment]
Yeap. This package is not done yet. =)

**Comment by julianpoemp** [comment]
@antonmedv do you have any plans creating this package? If not I would think about creating this as third-party-package

**Comment by antonmedv** [comment]
Sure. Go ahead)

**Comment by julianpoemp** [comment]
@antonmedv just released codejar-linenumbers: https://github.com/julianpoemp/codejar-linenumbers . It's compatible with CodeJar >= 4

**Comment by antonmedv** [comment]
Let’s add it to readme?

**Comment by julianpoemp** [comment]
@antonmedv that would be cool, yes :) I just released ngx-codejar v6 that supports CodeJar 4 with codejar-linenumbers.
