### ISSUE TITLE
cursor hides behind linenumbers

### ISSUE THREAD

**Issue by Zumbala** [antonmedv/codejar#109]
When using the linenumbers feature the editor position does not go back to zero.
![image](https://github.com/antonmedv/codejar/assets/7052083/5675c32d-c6b5-40dd-ac3c-4dc364670185)

To mitigate this, we can change the editor.scrollLeft position to 0 in the 2 functions

1. legacyNewLineFix
2. handleNewLine

**Comment by antonmedv** [comment]
line numbers feature was dropped from this package.

**Comment by Zumbala** [comment]
Please remove this feature than from your examples

This suggests that the extension is still available, but separate from your beautiful component.
