### ISSUE TITLE
Highlighting in second example breaks if I paste text into it

### ISSUE THREAD

**Issue by JobLeonard** [antonmedv/codejar#12]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/259840/81055925-f8aed700-8ec9-11ea-9dbd-3eac55617b1d.png">

I think there's a size-limit somehow because pasting small snippets works for a while. Maybe the bug is in the highlighting code, but maybe it's indicative of a subtle bug in CodeJar so I figured I'd open an issue

**Comment by antonmedv** [comment]
Due to big amount of dom nodes (one for each char) browsers can get struggling. So I added a limit in highlighting function. 

Note what this is really strange code example and for normal code, it won't be an issue.
