### ISSUE TITLE
Bug with highlight.js highlight function

### ISSUE THREAD

**Issue by gawlk** [antonmedv/codejar#18]
Hi !

There is a bug with the highlight.js highlight function

Here's what I see:

![Screen Shot 2020-06-09 at 9 05 43 PM](https://user-images.githubusercontent.com/32246972/84189117-ffb2a180-aa94-11ea-8888-4be70fa96456.png)

Here's what I should see:

![Screen Shot 2020-06-09 at 9 03 16 PM](https://user-images.githubusercontent.com/32246972/84188945-b5c9bb80-aa94-11ea-88f0-2e78d6b9912e.png)

It's only if I write the text, if I paste it, everything is fine

Just in case, here's how I initialized CodeJar:

```
CodeJar(editor, hljs.highlightBlock);
```

I also spotted this, not sure if this can help:

![out](https://user-images.githubusercontent.com/32246972/84190190-d1ce5c80-aa96-11ea-9fe4-f49e4f3abd17.gif)

Instead of replacing the span on edit, it seems that a new one is inserted inside the first one

**Comment by antonmedv** [comment]
There is a bug in highlight.js. It does not clear old tags. You can fix it via:
```js
  const highlight = editor => {
    // highlight.js does not trims old tags,
    // let's do it by this hack.
    editor.textContent = editor.textContent
    hljs.highlightBlock(editor)
  }
```
