### ISSUE TITLE
Selection doesn't preserve direction

### ISSUE THREAD

**Issue by aziis98** [antonmedv/codejar#2]
If I start a selection going left, as soon as I release the key the selection gets "reversed" and successive arrow key presses start modifing the selection on its right edge.

**Edit.** You are using `startContainer` and `endContainer` to save the selection and `setStart` and `setEnd` to restore it. A possible solution would be to use `Selection.anchorNode` and `Selection.focusNode` on save and [Selection.setBaseAndExtent](https://developer.mozilla.org/en-US/docs/Web/API/Selection/setBaseAndExtent) on restore.

**Comment by antonmedv** [comment]
`setBaseAndExtent` won't work as it doesn't work with char offsets. Will try to fix other side.

**Comment by antonmedv** [comment]
I've tryed:
```js
    var endRange = r.cloneRange();
    endRange.collapse(false);
    s.removeAllRanges();
    s.addRange(endRange);
    s.extend(r.startContainer, r.startOffset);
```
But no success.

**Comment by antonmedv** [comment]
Here is the snippet for detecting direction:
```ts
    function isSelectionBackward(sel: Selection) {
      var backward = false;
      if (!sel.isCollapsed) {
        var range = document.createRange();
        range.setStart(sel.anchorNode!, sel.anchorOffset);
        range.setEnd(sel.focusNode!, sel.focusOffset);
        backward = range.collapsed;
      }
      return backward;
    }
```

**Comment by aziis98** [comment]
I did a little spin off project reworking a bit the restore selection algorithm to use `setBaseAndExtent` and I think it works now: https://codepen.io/aziis98/pen/vYOMvex

**Comment by antonmedv** [comment]
This is awesome! Maybe PR to CodeJar?

**Comment by aziis98** [comment]
Thanks! Alright, I will work on that in the following days.

**Comment by antonmedv** [comment]
Fixed!
