### ISSUE TITLE
Deleting last line

### ISSUE THREAD

**Issue by junghoocho** [antonmedv/codejar#22]
When I delete all characters in the last line, the cursor moves up to the previous line, which is different from the typical behavior of most editors. In all editors that I am used to, the cursor still stays in the last line without moving up. I wonder whether this behavior is intentional and whether there is any way to change it (or add an option to let it behave differently).

![Jun-16-2020 09-32-42](https://user-images.githubusercontent.com/9000236/84801745-67e11600-afb4-11ea-84ff-fda892a29c9b.gif)

**Comment by antonmedv** [comment]
Is it in Chrome or Firefox? I assume this is contenteditable behaviour.

**Comment by junghoocho** [comment]
This is from Chrome and Safari. 

Firefox has a whole set of other problems and it is not usable for editing text.

**Comment by antonmedv** [comment]
Looks like chrome deletes newline and there is no new node for placeholding. This is behaviour of contenteditable. I think it’s possible to override with custom behaviour.

**Comment by antonmedv** [comment]
I was not able to find an appropriate solution for CodeJar yet. But here is a workaround if you'd like to add it in your custom highlight function.

Idea is to add extra `\n` at the end of the last line if there is none.

```js
  // Add new line at end every time
  let html = editor.textContent
  if (html.length > 2 && html.substring(html.length - 2, html.length) != '\n\n') {
    html += '\n'
  }
  editor.innerHTML = html
```
