### ISSUE TITLE
TS indentRegex Error

### ISSUE THREAD

**Issue by tom-cichy-cityos** [antonmedv/codejar#25]
https://github.com/antonmedv/codejar/blob/ea3508624c66a46dac421d0910dc40f1477979bc/codejar.ts#L220

Not found, maybe options.indentRegex ??

**Comment by tom-cichy-cityos** [comment]
That removes the TS watch error. I'll test it if it works overall.

**Comment by antonmedv** [comment]
You are right. This is due to latest code change.

**Comment by antonmedv** [comment]
Fixed in 3.1.0
