### ISSUE TITLE
cpp highlight not work

### ISSUE THREAD

**Issue by WxxShirley** [antonmedv/codejar#28]
Hi, I have used this in my react-app together with `highlight.js`.
There are several issues I have encountered:
* cpp highlight not work with highlight.js, my code:
  ```javascript
  import cpp from  'highlight.js/lib/languages/cpp';
  hljs.registerLanguage('cpp',cpp);
  ```
*  themes switch
    I use the method that once user clicks a new theme, corresponding  theme's `.css` file will be loaded, e.g.
   ```javascript
    require('highlight.js/styles/'+this.state.theme+".css");
   ```
   but in that mode, if I use theme a, then switch to theme b, then switch to theme a, theme won't be changed

**Comment by antonmedv** [comment]
How is this related to codejar?
