### ISSUE TITLE
undo/redo wrong key shortcut

### ISSUE THREAD

**Issue by rohusan** [antonmedv/codejar#29]
First let me tell you've done a great job! I love small & smart base codes.

**how it works**
undo: ctrl-y / redo: ctrl-shift-y

**expected**
undo: ctrl-z / redo: ctrl-y

I'm working on linux/windows with QWERTZ keyboard.

**Comment by NicolasFritz** [comment]
Hello :)

Noticed the same issue on Mac with CMD + Z / CMD+SHIFT+Z which does not work

**Comment by NicolasFritz** [comment]
Fix is available 👍
