### ISSUE TITLE
ReadOnly mode possible?

### ISSUE THREAD

**Issue by eouia** [antonmedv/codejar#32]
Thanks for your great job. 
I have a question/suggestion. Is there any feature of `readonly`? if not, it will be a great feature of this nice work.

And furthermore, it would be nicer if it is controllable by API on flight time. For example, `jar.readonly(true)` or something.

**Comment by antonmedv** [comment]
You can just set contenteditable to false.

**Comment by eouia** [comment]
Thanks. I'll try.
