### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by blunt1337** [antonmedv/codejar#34]
Hey ! Thanks for your awesome lib !

Can you update the package on npm to match the latest documentation ?
The option "addClosing" is missing from the published package (and there is a small typo "identOn" => "indentOn").
Thanks !

**Comment by antonmedv** [comment]
Can you make a PR to fix it? Thanks!

**Comment by blunt1337** [comment]
Done for the typo. But I can't do 'npm publish' for you :p

**Comment by antonmedv** [comment]
Will do it later today!

**Comment by blunt1337** [comment]
Thanks, you forgot to compile the .ts files to .js though

**Comment by antonmedv** [comment]
Ahh, will add automation to not forget it next time.

**Comment by antonmedv** [comment]
@blunt1337 please verify again.

**Comment by blunt1337** [comment]
Nope, still the old js

**Comment by antonmedv** [comment]
Well, now it's 99% working)

**Comment by blunt1337** [comment]
Thank it's all good!
