### ISSUE TITLE
Update withLineNumber with new highlight method

### ISSUE THREAD

**Issue by rathashit** [antonmedv/codejar#38]
Hello! 
I am using the `withLineNumber` module and there's this case of changing the highlight method according to the language selected by user.

Now as there are no means to update the `highlight` method using the instance created by `CodeJar`, I create a new instance of `CodeJar` and pass the new `highlight` method. When I do this, the `withLineNumber` function is adding new wrapper div on top of editor because of the `init` method being called every-time the language changes.

I was wondering if there was check like this in the `withLineNumbers` then it would just bypass the `init` process as it has already been initialised 
```
let lineNumbers = document.querySelector(` .${opts.class}`)
```

https://codesandbox.io/s/blissful-chaplygin-e794q?file=/src/App.js

or is there a better way to do this?

**Comment by antonmedv** [comment]
Some check can be made in withLineNumbers() I think. Or you just can wipeout entire div innerHTML.

**Comment by antonmedv** [comment]
Or just implement line-numbers by your self. Use CodeJar only for code.

**Comment by rathashit** [comment]
I'll try to implement the line-numbers for now but it would be great if there was a way to use withLineNumber in such scenarios.
