### ISSUE TITLE
Paste over selection

### ISSUE THREAD

**Issue by mike76-dev** [antonmedv/codejar#39]
When a part of text is selected, paste replaces it but the caret moves by textToPaste.length (desired) + selection.length (undesired). When no text is selected, the behavior is as expected.

**Comment by mike76-dev** [comment]
function handlePaste(event: ClipboardEvent) {
    preventDefault(event)
    const text = ((event as any).originalEvent || event).clipboardData.getData("text/plain")
    const s = window.getSelection()
    const selection = !s.isCollapsed
    const pos = save()
    insert(text)
    highlight(editor)
    if (selection) {
        restore({start: pos.end, end: pos.end})
    } else {
        restore({start: pos.end + text.length, end: pos.end + text.length})
    }
  }

**Comment by antonmedv** [comment]
Can you make pr this change?

**Comment by mike76-dev** [comment]
Done.

**Comment by antonmedv** [comment]
Your solution was wrong. Fixed it in 84aaec0442987fd4e5282a87c1b8fbc6bb6a428d

**Comment by mike76-dev** [comment]
Was it? Well, to be honest, I just used some of your code in browser js where it did show this issue and my solution was able to fix it. Sorry if it didn't work out for you. Appreciate your work though.
