### ISSUE TITLE
Configuring line numbers style?

### ISSUE THREAD

**Issue by karlicoss** [antonmedv/codejar#4]
Hi, I'm from lobste.rs! Trying out your library, and have few questions/suggestions regarding the line numbers.

At the moment line numbers style isn't configurabe (apart from the [width](https://github.com/antonmedv/codejar/blob/89df646b41c52eb9614df96460a8c08965768ad2/linenumbers.ts#L48)). Couple of suggestions that would help with it:

- do you think it makes sense to add a class element to the line numbers `div` (i.e. `.codejar-linenumbers`), that way it would be possible to retrieve it later and set/adjust the attributes dynamically?
- alternatively, the init function could take in. Although I feel that it's hard to anticipate what people might want to tweak, so to prevent the `Options` type from bloating, maybe it's enough to let the users set the style via normal means

Another thing is:  the default style is [while color on the transparent background](https://github.com/antonmedv/codejar/blob/89df646b41c52eb9614df96460a8c08965768ad2/linenumbers.ts#L50-L51). It looks nice on the dark editor block, but mine was white and at first I thought the line numbers weren't working. Maybe it makes sense to make the line numbers block background non-transparent by default, so it contrasts and is visible regardless the underlying block?

Let me know what you think, also happy to contribute when I get a bit of free time!

**Comment by antonmedv** [comment]
Hi,

I think the class will do the thing.  

Also about default colors; it uses `mix-blend-mode: difference;` and it will be "okay" looking on most of the themes (of course if your browser supports it). 

![image](https://user-images.githubusercontent.com/141232/78975710-56474200-7b1d-11ea-8c0a-493d43ce304c.png)

PS PR are welcome.

**Comment by antonmedv** [comment]
I've released new version with class names.
