### ISSUE TITLE
consider adding optional window parameter to CodeJar()

### ISSUE THREAD

**Issue by nealey** [antonmedv/codejar#50]
In order to get CodeJar working inside an iframe, I made the following change to the JavaScript (hopefully this is easy to port back to the TypeScript source):

```javascript
export function CodeJar(editor, highlight, window = window, opt = {}) {
    let document = window.document;
```

This adds an optional `window` parameter, which I can provide the iframe window for, and then all the getSelection() calls work. It also sets `document` from whatever `window` is, for the 6 locations CodeJar refers to it.

I was having numerous iframe problems with Ace: fixing it in CodeJar was much easier!

**Comment by antonmedv** [comment]
Can you show html example of what you are trying to do?

**Comment by nealey** [comment]
Certainly!

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="edit.js"></script>
  </head>
  <body>
    <h1>Top-level</h1>
    <iframe srcdoc="Nothing here yet"></iframe>
  </body>
</html>
```

```javascript
function dostuff(CodeJar) {
  let win = document.querySelector("iframe").contentWindow
  let doc = win.document
  while (doc.body.firstChild) {
    doc.body.firstChild.remove()
  }
  doc.body.appendChild(doc.createElement("h2")).textContent="iframe"
  let editor = doc.body.appendChild(doc.createElement("div"))
  let jar = CodeJar(editor, () => null)
  jar.updateCode("void main() {while fork() fork();}")
  editor.style.background = "#eee"
 }
import("https://medv.io/codejar/codejar.js")
.then((m) => dostuff(m.CodeJar))
```

Live demo: https://jsfiddle.net/fLz87mxe/

Insert text and observe the js console, complaining about selection index of 0. This is because when `window.getSelection` is called, 'window' is the top-level window, and not the window associated with the iframe.

**Comment by antonmedv** [comment]
Fixed!
