### ISSUE TITLE
Toolbar for markup languages?

### ISSUE THREAD

**Issue by erickilisboa** [antonmedv/codejar#51]
It would be a boon for users of markdown and textile (even more because it does not depend on a specific syntax highlight) a toolbar for these languages. Or for one of them, but easily modified for others. The options currently available are often quite heavy and cannot be used with external syntax highlighting.

**Comment by antonmedv** [comment]
I think a such toolbar can be easily implemented. But it out of the scope of the current CodeJar agenda. CodeJar trying to be a language-agnostic editor.

**Comment by erickilisboa** [comment]
I am trying to create a simple toolbar, however I have a problem. The undo feature does not work for the content inserted by the toolbar.

Is there something wrong with this?

```javascript
function wrap(tag) {
  jar.recordHistory();

  sel = window.getSelection();
  if (sel.rangeCount) {
    range = sel.getRangeAt(0);
    range.insertNode(document.createTextNode(tag));
    range.collapse();
    range.insertNode(document.createTextNode(tag));
  }

  jar.updateCode(jar.toString());
}
```

**Comment by antonmedv** [comment]
Now there is a method: recordHistory.
