### ISSUE TITLE
Cursor Position is not restored correctly when pasting multiple lines

### ISSUE THREAD

**Issue by zavierboyd** [antonmedv/codejar#52]
Hi

CodeJar does not restore the cursor position correctly when pasting multiple lines. I have encountered this on Windows computers and the Chrome browser. I also tested this on the latest CodeJar on the front page of the CodeJar website.

This is encountered because CodeJar counts `\r` as a character, but when Chrome pastes the text it gets rid of the `\r` leaving just `\n`. So the cursor position moves forward instead of correctly restoring.

Example:
``` javascript
// Start state
text = 'a'
cursorPos = 0 // cursor is at beginning of text
clipboard = 'b\r\n1'
```
1. CodeJar inserts the clipboard 
1. The browser gets rid of `\r` and inserts the clipboard
1. CodeJar restores the position using `text.length` which counts `\r`
``` javascript
// End state
text = 'b\n1a'
cursorPos = 4 // cursor is at end of text
clipboard = 'b\r\n1'
```
From this the cursor position is now 1 space ahead of where it should be.
This increases for each new line copy-pasted this way.

Potential Fix:
I have created a potential fix for this bug by changing the `handlePaste` function to:
``` typescript
function handlePaste(event: ClipboardEvent) {
  preventDefault(event)
  let text = ((event as any).originalEvent || event).clipboardData.getData('text/plain')
  text = text.replace(/\r/g, '') // This gets rid of any \r characters in the clipboard
  const pos = save()
  insert(text)
  highlight(editor)
  restore({ start: pos.start + text.length, end: pos.start + text.length })
}
```

**Comment by antonmedv** [comment]
Fixed!
