### ISSUE TITLE
Cursor keeps jumping back to start when using Prism highlighter

### ISSUE THREAD

**Issue by purringChaos** [antonmedv/codejar#54]
To test simply load the UIKit javascript into your example html or website.

**Comment by purringChaos** [comment]
Note that this only happens when UIKit is loaded before codejar is.
Maybe the keyup/down handler breaks? no idea.

**Comment by purringChaos** [comment]
Wait nevermind, it seems to only do it when using prism as a highlighter 
with highlight = `() => {}` it does not do this.

I am on latest Edge Dev build on Linux.

**Comment by antonmedv** [comment]
Can you create prism example on codesandbox?

**Comment by purringChaos** [comment]
doesnt seem to do it on codesandbox, try using edge and playing around with uikit, no idea

**Comment by purringChaos** [comment]
highlight = `() => {}`: http://transfer.sh/liyyI/Screencast%20from%2011-04-21%2016:53:35.webm
highlight = `Prism.highlightElement`: http://transfer.sh/rPeu2/Screencast%20from%2011-04-21%2016:57:21.webm

i will tarball up my html as a simple example, give me a bit

**Comment by antonmedv** [comment]
I can’t reproduce it :srug:

**Comment by purringChaos** [comment]
I CAN REPRODUCE woot!
hold up or a minute

**Comment by purringChaos** [comment]
http://transfer.sh/IANkG/test.tar
here, run this on latest edge dev on a local webserver (file:// gives prism webworker errors)

**Comment by purringChaos** [comment]
bump

**Comment by purringChaos** [comment]
can still reproduce, whenever you press backspace it jumps to beginning, so i cant use syntax highlighting.
does it on ireox and edge.

**Comment by thdoan** [comment]
Same issue when using [CodeJar](https://medv.io/codejar/). I resolved the issue by switching to Highlight, as used by the demo on CodeJar.
