### ISSUE TITLE
Set language markup for PrismJS

### ISSUE THREAD

**Issue by Cannonb4ll** [antonmedv/codejar#56]
Having this code:

```js
let jar = new CodeJar(document.getElementById(this.name), PrismJS.highlightElement);
```

How does someone tell to this it needs to use the `php` language as highlight, or `css` for example?

I tried setting the `language-php` class to the div, but no dice.

Thanks!

**Comment by antonmedv** [comment]
Hi, this is prismjs related question. Also take a look how it’s done on website.

**Comment by accountnujen** [comment]
> Hi, this is prismjs related question. Also take a look how it’s done on website.

не, проблема в том, что в данном случае вообще никакой подсветки нет.
Вот я взял из инструкции на главной странице: https://jsfiddle.net/72ujLfp5/
У меня получилось завести только вот таким образом: https://codepen.io/djalmajr/details/yLobmBK

Но тогда появляется вопрос: а как можно на лету изменить язык?
Я сделал вот так: https://jsfiddle.net/801spqj5/ , но есть сомнения, что это верный способ, потому что я просто заново инициализирую CodeJar.

**Comment by antonmedv** [comment]
В функции hightlight используй замыкание на переменной язык.

**Comment by accountnujen** [comment]
> В функции hightlight используй замыкание на переменной язык.

подскажите пожалуйста, как?

**Comment by antonmedv** [comment]
https://learn.javascript.ru/

**Comment by accountnujen** [comment]
> https://learn.javascript.ru/

ну и где у тебя замыкание переменной
![Снимок экрана 2022-01-24 204846](https://user-images.githubusercontent.com/91395439/150836794-534e1c50-c257-410c-a183-051764dc0920.png)

ты хотя бы тестировал перед тем как выставлять? Твой код не работает.
Ещё раз: 
https://jsfiddle.net/72ujLfp5/ - здесь сделано в точности, как у тебя написано и оно, представь себе, не работает.

**Comment by accountnujen** [comment]
тебя выбесило, что я спросил о том , как сделать, чтобы работало и ты скинул ссылку на учебник, однако **не я накосячил в инструкции.** Прочтение учебника не изменит твой код.

**Comment by antonmedv** [comment]
Я бы на твоем месте не хамил, а начал бы с основ программирования. Без основ далеко не уедешь.

**Comment by accountnujen** [comment]
> Я бы на твоем месте не хамил, а начал бы с основ программирования. Без основ далеко не уедешь.

проблема в том, что я читал learn.javascript и чёт там не было ничего про **### замыкание на переменный язык**. Очень круто ты реагируешь на критику: "Если не работает, значит все остальные неправильные, а не ты инструкции писать не умеешь". Удаляй репозиторий тогда, раз он не работает.

**Comment by antonmedv** [comment]
Рекомендую начать с прочтения https://ru.wikihow.com/обучиться-хорошим-манерам

**Comment by antonmedv** [comment]
И там всё есть https://learn.javascript.ru/closure

**Comment by Cannonb4ll** [comment]
Guys, fun and all. But please talk english for future members that visit this issue and have no clue what you're on about.

**Comment by antonmedv** [comment]
TLDR: a school student needs to learn JS first.

**Comment by accountnujen** [comment]
> Рекомендую начать с прочтения [https://ru.wikihow.com/обучиться-хорошим-манерам](https://ru.wikihow.com/%D0%BE%D0%B1%D1%83%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%BC-%D0%BC%D0%B0%D0%BD%D0%B5%D1%80%D0%B0%D0%BC)

забавно, что человек, который даже близко не знаком с "хорошими" манерами пытается обучить этому других. Я ему говорю: "смотри, у тебя ошибка", а он мне: "ты чо мне хамишь?". Идиотизм https://www.youtube.com/watch?v=YyitPXvojsw

**Comment by antonmedv** [comment]
Если ошибка есть, я её поправлю как будет время. 

Пока можешь заняться изучением «джаваскрипта».

**Comment by antonmedv** [comment]
Задачка: привести пример замыкания.
