### ISSUE TITLE
Firefox enter before certain characters doesn't move cursor to the new line

### ISSUE THREAD

**Issue by craigengland** [antonmedv/codejar#57]
https://user-images.githubusercontent.com/1711923/115871530-96cbe200-a438-11eb-8b8c-97d812a89b6a.mov

When typing the first line and I press "Enter" the cursor and the final `'` follow me down to the next line.

In my second example when pressing "Enter" before the `?`, a new line is created however the cursor doesn't follow me in this scenario.

I have tested in Chrome and Safari and all works well on those browsers so I am guessing it has something to do with the `firefoxNewLineFix` function that intercepts the "Enter" key and adds a new line.

**Comment by antonmedv** [comment]
Yes, firefox is really buggy with contenteditable. A few bugs 4-5 y/o in firefox bug queue. 
Please, take a look at one of PRs. I think we have a fix there, but I still don’t have time to take a look at it.
