### ISSUE TITLE
Scroll on new line

### ISSUE THREAD

**Issue by privatenumber** [antonmedv/codejar#6]
When I press return to make new lines to the point it overflows or out of viewport, the scroll doesn't follow the caret.

I think this is will be a pretty intuitive feature as it's common in most text editors. Sublime does it, and even this textarea I'm typing in does it.

**Comment by antonmedv** [comment]
As soon as you type some char it will scroll down. With new lines there is some bug in browsers. Will try to fix it.

**Comment by antonmedv** [comment]
I've tried to solve it with something like this:
```js
      document.execCommand("insertHTML", false, "<div id=\"c\">\u200b</div>")
      const cursor = editor.querySelector("#c")
      if (cursor) {
        cursor.scrollIntoView({block: "end", inline: "nearest"})
        cursor.parentNode!.removeChild(cursor)
      }
```
I't works on new line at the end, but jumps in the middle. maybe another solution is needed.

**Comment by privatenumber** [comment]
I might re-consider the use of `execCommand` here as I'm reading it's an [obsolete feature](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).

Avoiding it would also force node creation + insertion, which is convenient because we would already have a reference to it to invoke `scrollTo` on.

**Comment by antonmedv** [comment]
Tagging?

**Comment by privatenumber** [comment]
Edited to clarify phrasing.

**Comment by antonmedv** [comment]
> I'm thinking somehow implementing the indentation/curly-bracket features without invoking preventDefault would be a cleaner approach.

Yes, this is a nice idea. Only one problem: FireFox.

**Comment by antonmedv** [comment]
For little bit improvement preventDefault can be called only if there is a padding:
```
if (newLinePadding.length > 0) {
        event.preventDefault()
        insertText(newLinePadding)
      }
```

**Comment by antonmedv** [comment]
I've updated CodeJar. Now if there is no ident default behavior is used.

**Comment by antonmedv** [comment]
Partially fixed.
