### ISSUE TITLE
Jar sets editor resize style to 'vertical' by default

### ISSUE THREAD

**Issue by kargirwar** [antonmedv/codejar#63]
Jar sets editor resize style to 'vertical' by default. What is the purpose behind this behavior? 
Ideally it should be optional. I am having to do the following:

```
        let editor = document.querySelector('#query-editor')
        const highlight = (editor) => {
            const code = editor.textContent
            // Do something with code and set html.
            editor.innerHTML = code
        }

        this.jar = CodeJar(editor, highlight)
        editor.style.resize = 'none';
```

**Comment by antonmedv** [comment]
I don’t remember why i set it to vertical by default. What is your use case?

**Comment by kargirwar** [comment]
I wanted to resize the editor myself. The default resize style interferes with that.

**Comment by antonmedv** [comment]
Fixed.
