### ISSUE TITLE
 Incorrect positioning of the cursor when pasting with a right-to-left selection

### ISSUE THREAD

**Issue by zazaulola** [antonmedv/codejar#70]
If you select text from right to left and then paste another text in its place, the cursor has the wrong position after pasting.

https://user-images.githubusercontent.com/75137033/133139219-f2f30d5f-2d17-471e-a446-b105a39e3845.mp4

**Comment by antonmedv** [comment]
Looks like a bug. Can you write a PR with a fix?

**Comment by Paktusin** [comment]
https://github.com/antonmedv/codejar/pull/77
