### ISSUE TITLE
undo event not working on german keyboard layout

### ISSUE THREAD

**Issue by Coding-Kiwi** [antonmedv/codejar#73]
When using the german qwertz layout, pressing cltr + z does nothing because the z key is KeyY

Keyboard events are messy in javascript, the [mozilla docs](https://developer.mozilla.org/de/docs/Web/API/KeyboardEvent) marks `event.which`, `event.keyCode` and `event.charCode` as deprecated and tells you to use `event.key` but as the PR https://github.com/antonmedv/codejar/pull/58 shows, `event.key` might be 'z' in german and english, no matter what layout but 'я' in russian.

I don't know why they deprecate all numeric properties and give us no alternative and the [keyboard.getLayoutMap](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap) api is still experimental.
But it should also be noted that big libraries like mousetrap also rely on `event.keyCode` and many many js projects use the classic `if event.keyCode === 13` to check for enter, so its not sure if it will ever be deprecated since it would break a lot of code.

What do you think about using `event.keyCode` ?

I would suggest as a fix you could make the isUndo and isRedo functions somehow configurable, that way we could also configure it to be ctrl+z for undo and ctrl+y for redo instead of ctrl+z and ctrl+shift+z

**Comment by antonmedv** [comment]
Yes, it should be fixed.

**Comment by antonmedv** [comment]
Fixed in release 3.7.0
