### ISSUE TITLE
Bug: autoClosing Braces and Parentheses have incorrect indent

### ISSUE THREAD

**Issue by tuckergordon** [antonmedv/codejar#76]
It looks like the behavior of the auto closing braces and parentheses does not match that of the brackets.

Consider the following options:
```js
let options = {
  indentOn: /[{\\([]$/,  // indent on {, (, and [
  addClosing: true
}
```
If I have this code in my editor
```json
{
  "a": 1,
  "b": {}
}
```
then place my cursor inside the `{}` and press return, it results in this:
```json
{
  "a": 1,
  "b": {
  	
  }
}
```
which is expected. However, following a similar procedure with braces or parentheses results in this:
```json
{
  "a": 1,
  "b": [
  	]
}
```

I would expect that, because braces and parentheses are included in the behaivor of `addClosing`, that they would indent in the same way as braces:
```json
{
  "a": 1,
  "b": [
  	
  ]
}
```

**Comment by TomFevrier** [comment]
@tuckergordon, seems like the author does not intend to fix and improve this buggy library, and is not open to anyone doing so... What a shame, it did seem promising.

**Comment by antonmedv** [comment]
Fixed! Now there is a separate regexp to test which lines to move on:
```
    indentOn: /[({\[]$/,
    moveToNewLine: /^[)}\]]/,
```
