### ISSUE TITLE
Strg+A Strg+C copies only subselection in Firefox (when plaintext-only is not supported)

### ISSUE THREAD

**Issue by Gnietschow** [antonmedv/codejar#88]
When I use Strg+A to select all content in Firefox and then Strg+C to copy it, it won't copy the whole content. It can easily tested by opening https://medv.io/codejar/ in Firefox and trying that in the first code editor.

I tracked that issue down to the line
`if (isLegacy)
            restore(save());`
in the keydown handler, which seems to move the selection end unexpectedly before the copy is handled.

**Comment by Gnietschow** [comment]
Understandable :) Do you remember for which case the line was added? If I remove it, it seems to work normally for me. But of course I'm not seeing the whole picture.

**Comment by antonmedv** [comment]
Not remember unfortunately. I’ll gonna try to add some test to cover this part.

**Comment by antonmedv** [comment]
Released 3.7.0
